name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  schedule:
    - cron: "*/15 * * * *"
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          LUXMED_LOGIN: ${{ secrets.LUXMED_LOGIN }}
          LUXMED_PASSWORD: ${{ secrets.LUXMED_PASSWORD }}
          LUXMED_LOGIN_KID: ${{ secrets.LUXMED_LOGIN_KID }}
          LUXMED_PASSWORD_KID: ${{ secrets.LUXMED_PASSWORD_KID }}
        run: npx playwright test
      - name: Extract failed names
        if: failure()
        id: report
        run: |
          export REPORT=$(node -e 'console.log(require("./test-results.json").suites.map(suite => suite.specs[0]).filter(spec => !spec.ok).map(spec => spec.title).join(","))')
          echo $REPORT
          echo "::set-output name=REPORT::$REPORT"
